"""create ingredients and recipe units tables

Revision ID: 56f5a330078b
Revises: 
Create Date: 2026-05-15 12:57:24.575743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f5a330078b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('purchase_unit', sa.String(length=50), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usage_unit', sa.String(length=50), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('yield_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_category'), 'ingredients', ['category'], unique=False)
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_is_active'), 'ingredients', ['is_active'], unique=False)
    op.create_table('recipe_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_recipe_units_id'), 'recipe_units', ['id'], unique=False)
    op.create_table('ingredient_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_price_history_id'), 'ingredient_price_history', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_price_history_ingredient_id'), 'ingredient_price_history', ['ingredient_id'], unique=False)
    op.create_table('ingredient_recipe_unit_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_unit_id', sa.Integer(), nullable=False),
    sa.Column('usage_unit_quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_unit_id'], ['recipe_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'recipe_unit_id', name='uq_ingredient_recipe_unit')
    )
    op.create_index(op.f('ix_ingredient_recipe_unit_conversions_id'), 'ingredient_recipe_unit_conversions', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_recipe_unit_conversions_ingredient_id'), 'ingredient_recipe_unit_conversions', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_recipe_unit_conversions_ingredient_id'), table_name='ingredient_recipe_unit_conversions')
    op.drop_index(op.f('ix_ingredient_recipe_unit_conversions_id'), table_name='ingredient_recipe_unit_conversions')
    op.drop_table('ingredient_recipe_unit_conversions')
    op.drop_index(op.f('ix_ingredient_price_history_ingredient_id'), table_name='ingredient_price_history')
    op.drop_index(op.f('ix_ingredient_price_history_id'), table_name='ingredient_price_history')
    op.drop_table('ingredient_price_history')
    op.drop_index(op.f('ix_recipe_units_id'), table_name='recipe_units')
    op.drop_table('recipe_units')
    op.drop_index(op.f('ix_ingredients_is_active'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_category'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
