"""add recipe_sub_recipes, size_packaging and store_products tables

Revision ID: 89c7ea73ba3a
Revises: 00b0e796bee1
Create Date: 2026-05-15 13:07:20.521254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c7ea73ba3a'
down_revision: Union[str, None] = '00b0e796bee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_sub_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_product_id', sa.Integer(), nullable=False),
    sa.Column('sub_recipe_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('scales_with_size', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sub_recipe_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_sub_recipes_id'), 'recipe_sub_recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_sub_recipes_parent_product_id'), 'recipe_sub_recipes', ['parent_product_id'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('seasonal_start_date', sa.Date(), nullable=True),
    sa.Column('seasonal_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_store_product')
    )
    op.create_index(op.f('ix_store_products_id'), 'store_products', ['id'], unique=False)
    op.create_index(op.f('ix_store_products_store_id'), 'store_products', ['store_id'], unique=False)
    op.create_table('size_packaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('packaging_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['packaging_ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['product_sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_size_packaging_id'), 'size_packaging', ['id'], unique=False)
    op.create_index(op.f('ix_size_packaging_size_id'), 'size_packaging', ['size_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_size_packaging_size_id'), table_name='size_packaging')
    op.drop_index(op.f('ix_size_packaging_id'), table_name='size_packaging')
    op.drop_table('size_packaging')
    op.drop_index(op.f('ix_store_products_store_id'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_id'), table_name='store_products')
    op.drop_table('store_products')
    op.drop_index(op.f('ix_recipe_sub_recipes_parent_product_id'), table_name='recipe_sub_recipes')
    op.drop_index(op.f('ix_recipe_sub_recipes_id'), table_name='recipe_sub_recipes')
    op.drop_table('recipe_sub_recipes')
    # ### end Alembic commands ###
