"""create stores and store ingredient prices tables

Revision ID: bec9f22bb47c
Revises: 56f5a330078b
Create Date: 2026-05-15 13:00:23.499259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec9f22bb47c'
down_revision: Union[str, None] = '56f5a330078b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_table('store_ingredient_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('local_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('local_supplier', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ingredient_id', name='uq_store_ingredient')
    )
    op.create_index(op.f('ix_store_ingredient_prices_id'), 'store_ingredient_prices', ['id'], unique=False)
    op.create_index(op.f('ix_store_ingredient_prices_store_id'), 'store_ingredient_prices', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_ingredient_prices_store_id'), table_name='store_ingredient_prices')
    op.drop_index(op.f('ix_store_ingredient_prices_id'), table_name='store_ingredient_prices')
    op.drop_table('store_ingredient_prices')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
