"""create products and product sizes tables

Revision ID: 7c2137860bf0
Revises: bec9f22bb47c
Create Date: 2026-05-15 13:02:30.923689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2137860bf0'
down_revision: Union[str, None] = 'bec9f22bb47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('base_size_oz', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('prep_time_minutes', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('labor_cost_per_minute', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_sub_recipe', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_sub_recipe'), 'products', ['is_sub_recipe'], unique=False)
    op.create_table('product_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size_name', sa.String(length=50), nullable=True),
    sa.Column('volume_oz', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('scale_factor', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_name', name='uq_product_size_name')
    )
    op.create_index(op.f('ix_product_sizes_id'), 'product_sizes', ['id'], unique=False)
    op.create_index(op.f('ix_product_sizes_product_id'), 'product_sizes', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sizes_product_id'), table_name='product_sizes')
    op.drop_index(op.f('ix_product_sizes_id'), table_name='product_sizes')
    op.drop_table('product_sizes')
    op.drop_index(op.f('ix_products_is_sub_recipe'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
